name: First Workflow

on: 
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "Welcome to our first github action workflow!"

      - name: checkout repo
        uses: actions/checkout@v5.0.0
      
      - name: list files
        run: ls -la
